apiVersion: apps/v1
kind: Deployment
metadata:
  name: linux-runner
  namespace: gitaction
  labels:
    app: linux-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linux-runner
  template:
    metadata:
      labels:
        app: linux-runner
    spec:
      containers:
      - name: runner
        image: runner:latest
        env:
        - name: GITHUB_OWNER
          value: avidunken
        - name: GITHUB_REPOSITORY
          value: jenkins-pipeline
        - name: GITHUB_PERSONAL_TOKEN 
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: GITHUB_PERSONAL_TOKEN
